"""Tables were art thou?

Revision ID: 8f1f9a352fb0
Revises: f9bc6b028f75
Create Date: 2024-06-12 18:36:51.806338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f1f9a352fb0'
down_revision: Union[str, None] = 'f9bc6b028f75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
